extreload: Try parsing `GetTargets` response
Tried to parse the response from the `GetTargets` message, but ended up
with this error:

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
    value: Error("unknown variant `iframe`, expected one of `page`,
    `background_page`, `service_worker`, `browser`, `other`", line: 0,
    column: 0)',
    /Users/tw/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.9.0/src/protocol/mod.rs:90:70

Looks like the `headless_chrome` library doesn't include "iframe" as a
`TargetType`:
https://docs.rs/headless_chrome/0.9.0/headless_chrome/protocol/target/enum.TargetType.html

Will have to modify the library, use a different library, or write my
own types to serialize & deserialize.